--Average Value Of Orders
SELECT TOP(20) A.CUSTOMERKEY,A.FIRSTNAME +' '+A.LASTNAME AS CUSTOMERNAME ,CAST( SUM(SALESAMOUNT) AS DECIMAL(9,2)) AS 'AVERAGE SALES ORDER($)'
FROM DIMCUSTOMER A JOIN FACTPRODUCTSALESORDER B 
ON A.CUSTOMERKEY=B.CUSTOMERKEY
GROUP BY A.CUSTOMERKEY, A.FIRSTNAME, A.LASTNAME
HAVING SUM(SALESAMOUNT) > (SELECT SUM(SALESAMOUNT)/COUNT(CUSTOMERKEY) FROM FACTPRODUCTSALESORDER)
ORDER BY SUM(SALESAMOUNT) DESC

--Total Sales Return
SELECT COUNT(CUSTOMERKEY) AS 'TOTAL SALES RETURN', CAST( COUNT(CUSTOMERKEY)*100./(SELECT COUNT(*) FROM DIMCUSTOMER) AS DECIMAL(9,2)) AS 'SALES RETURN PERCENT(%)'
FROM DIMCUSTOMER
WHERE CUSTOMERKEY IN (SELECT CUSTOMERKEY
FROM FACTPRODUCTSALESORDER
GROUP BY CUSTOMERKEY
HAVING SUM(SALESAMOUNT)>(SELECT SUM(SALESAMOUNT)/COUNT(CUSTOMERKEY) FROM FACTPRODUCTSALESORDER))

--Routing Efficiency
SELECT	CAST(
COUNT(*) * 100. / 
(SELECT COUNT(*) 
FROM FACTWORKORDERROUTING) AS DECIMAL(9,2)
) AS '(%) ACTUAL COST / PLANNED COST' 
FROM FACTWORKORDERROUTING
WHERE PLANNEDCOST = ACTUALCOST

--SCRAPPED PRODUCTS QUANTITY CATEGORIZED INTO MODELS
SELECT    	MODEL ,
         	SUM(SCRAPPEDQUANTITY) AS 'TOTAL SCRAPPED QUANTITY'
FROM DIMPRODUCT A
JOIN FACTWORKORDERROUTING B ON A.PRODUCTID=B.PRODUCTID
GROUP BY MODEL
ORDER BY SUM(SCRAPPEDQUANTITY) DESC


--Scrapped Products Quantity Categorized Into Category
SELECT    	CATEGORY ,
         	SUM(SCRAPPEDQUANTITY) AS 'TOTAL SCRAPPED QUANTITY'
FROM DIMPRODUCT A
JOIN FACTWORKORDERROUTING B ON A.PRODUCTID=B.PRODUCTID
GROUP BY CATEGORY
ORDER BY SUM(SCRAPPEDQUANTITY) DESC

--Scrapped Products Quantity Categorized Into Subcategory
SELECT	SUBCATEGORY ,
   		SUM(SCRAPPEDQUANTITY) AS 'TOTAL SCRAPPED QUANTITY'
FROM DIMPRODUCT A
JOIN FACTWORKORDERROUTING B ON A.PRODUCTID=B.PRODUCTID
GROUP BY SUBCATEGORY
ORDER BY SUM(SCRAPPEDQUANTITY) DESC

--Routing Effectiveness
SELECT	CAST(
         		COUNT(*) * 100. /
                		(SELECT COUNT(*)
                		FROM FACTWORKORDERROUTING) AS DECIMAL(9,2)
) AS '(%) TOTAL WORK ORDERS DELIVERED LATELY / TOTAL WORKORDER'
	FROM FACTWORKORDERROUTING
WHERE SCHEDULEDENDDATE != ACTUALENDDATE


